### PR TITLE
Snapshot testing

### PR DESCRIPTION
**Pull request by zbyte64**
This not only adds snapshot testing to the generated application, but the `npm test` script was modified to also run the generated tests in a docker environment. This significantly adds to the test time (note the increased test timeout) but allowed me to quickly iterate; python dependency errors get caught :)

### CODE REVIEW

**Comment by zbyte64** [comment]
I'm having trouble spotting the syntax error for node v4 and the trace isn't helpful :(

**Comment by metakermit** [comment]
Oh nice, I didn't know Travis added Docker tests (very cool – @alicetragedy here's a virtual 🙌 to whoever's responsible for that in the office 🙂).

@zbyte64 if it's just node v4 failing, I think it's safe to remove it. I only added it because it was in the default generator-generator template. The LTS is v8 anyway.

**Comment by zbyte64** [comment]
And it's fixed.

**Comment by metakermit** [comment]
Perfect, thanks 😊👌

**Pull request merged**
